testingapp/urls.py
from django.contrib import admin
from django.urls import path
from . import views 
from django.contrib.auth import views as auth_views
from .models import post,photo
from .views import postDetailView, postListView,dashpostview,post_chart,save_location,add_to_favorites,favorite_list,liked_recipes,delete_image,Updaterecipeview,Deletepost,UpdatePassword,acc_settings, UpdateProfile,trendingview,customer_render_pdf_view,like_view,dislike_view,new_page
from .views import custom_cards,delete_account,year_recap,credits,cuisines,gsap,scroll,summarize_content,generate_recipe_with_ai_image,generate_recipe,email_template,remove_notification,delete_all_blog_history,clear_all_notifications
from .views import CustomPasswordResetView,CustomPasswordResetDoneView,CustomPasswordResetConfirmView,CustomPasswordResetCompleteView
from django.views.i18n import set_language



urlpatterns = [
    path('',views.landingpg,name="landingpg"),

    path('password_reset/', CustomPasswordResetView.as_view(), name='password_reset'),
    
    path('password_reset/done/', CustomPasswordResetDoneView.as_view(), name='password_reset_done'),
    
    path('reset/<uidb64>/<token>/', CustomPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    
    path('reset/done/', CustomPasswordResetCompleteView.as_view(), name='password_reset_complete'),

    path('newnavbar_navrail',views.newnavbarnavrail,name="newnavbarnavrail"),
    
    path('explore/',postListView.as_view(),name="explore"),
    
    path('home/',dashpostview.as_view(),name="home"),
    
    path('login/',views.login_view,name="login"),   
    
    path('login_required/<pk>/',views.topostlogin,name="topostlogin"),
    
    path('signup/',views.signup_view,name="signup"),
    
    path('logout/',views.logout_view,name="logout"),
    
    path('profile/',views.profile_view,name="profile"),
    
    path('newrecipe/',views.post_post_view,name="createpost"), 
    
    path('searchresults/',views.searchresults_view,name="searchresults"),
    
    path('aa/',views.aa_view,name="aa"), 
    
    path('recipe/<pk>/',postDetailView.as_view(),name="viewpost"), #post
    
    path('post/comment',postDetailView.as_view(),name="comment"),

    path('like-view/',views.like_view,name="like-view"),
    
    path('dislike/',views.dislike_view,name="dislike-view"),

    # path('like/<int:pk>',views.like_view,name="likes"),

    # path('<first>_<last>/<pk>',views.userchannel,name="userchannelpage"),

    path('user_channel/<pk>/',views.userchannel,name="userchannelpage"),

    path('dashboard/',views.dashboard,name="dashboard"),

    path('delete/<int:pk>/',Deletepost.as_view(),name="delete"),

    path('updaterecipe/<title>/<pk>/',views.Updaterecipeview,name="updaterecipe"),
    
    path('delete_image/<int:image_pk>/', views.delete_image, name='delete_image'),

    path('updateprofile/',views.UpdateProfile,name="updateprofile"),
    
    path('changepassword/',UpdatePassword.as_view(),name="updatepassword"),

    path('account_settings/',views.acc_settings,name="account_settings"),

    path('liked_recipes/',views.liked_recipes,name="liked_recipes"),

    path('<feed>/<pk>/download pdf/',views.customer_render_pdf_view,name="customerrender"),

    path('trending/',trendingview.as_view(),name="trending"),

    path('timeline/',views.timeline,name="timeline"),

    path('history/', views.blog_history, name='blog_history'),

    path('delete_entry/<pk>/', views.delete_entry, name='delete_blog'),

    path('delete_entry/', views.bulk_delete_blogs, name='bulk_delete'),

    path('delete-all/', views.delete_all_blog_history, name='delete_all_blog_history'),

    path('delete_account/', views.delete_account, name='delete_account'),

    path('recap/',views.year_recap,name="year_recap"),

    path('appearance/',views.appearance,name="appearance"),

    path('reset_colors/', views.reset_colors, name='reset_colors'),

    path('reset_dark_theme/', views.reset_dark_theme, name='reset_dark'),

    path('new_color_palette/', views.default_color_palette1, name='dcp_1'),

    path('save_location/', save_location, name='save_location'),

    path('fav/<int:id>/', views.add_to_favorites, name='add_to_favorites'),

    path('favourites/', views.favorite_list, name='favourites'),

    path('post_chart/', views.post_chart, name='post_chart'),

    path('<slug>',views.custom_cards,name="custom_cards"),

    path('credits/',views.credits,name="credits"),

    path('cuisines/<slug>/',views.cuisines,name="cuisines"),

    path('new-page/', views.new_page, name='new_page'),

    path('gsap/', views.gsap, name='gsap'),

    path('scroll/', views.scroll, name='scroll'),

    path('summarize/', summarize_content, name='summarize_content'),

    path('KitchenAI/', views.generate_recipe_with_ai_image, name='generate_recipe'),

    path('KitchenAI/', views.generate_recipe, name='generaterecipe'),
    
    path('email_template/', views.email_template, name='email_template'),

    path('remove_notification/', views.remove_notification, name='remove_notification'),

    path('clear_all_notifications/', views.clear_all_notifications, name='clear_all_notifications'),

]

testingapp/models.py
from cProfile import Profile
from distutils.command.upload import upload
from email.policy import default
# from hashlib import new
from django.db import models
from django.utils import timezone
import math
from django.contrib.auth.models import User
from django.urls import reverse
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, BaseUserManager
from hitcount.models import HitCountMixin, HitCount
from django.contrib.contenttypes.fields import GenericRelation

from ckeditor.fields import RichTextField
from django.core.validators import MinValueValidator

from django.core.files.storage import default_storage
from storages.backends import s3boto3
import os
# Create your models here.


class profile(models.Model):

    GENDER_CHOICES = (
        ('Male', 'Male'),
        ('Female', 'Female'),
    )

    user = models.OneToOneField(User,on_delete=models.CASCADE)
    profile_img = models.ImageField(default='avatar.jpg',upload_to='profile')
    dob = models.DateField(null=True, blank=True)
    gender = models.CharField(max_length=20, choices=GENDER_CHOICES, null=True, blank=True)
    bio = models.TextField(default='Bio')
    hit_count = models.OneToOneField(HitCount, null=True, blank=True, on_delete=models.CASCADE)
    send_email = models.BooleanField(default=True)
    credits = models.IntegerField(default=10, validators=[MinValueValidator(0)])
    earned_credits = models.IntegerField(default=0, validators=[MinValueValidator(0)])
    redeemed_credits = models.IntegerField(default=0, validators=[MinValueValidator(0)])
    credits_spent = models.PositiveIntegerField(default=0)

    # credits = models.DecimalField(default=5, max_digits=10, decimal_places=2)

    
    def __str__(self):
        return self.user.username + " Profile"


    # def get_absolute_url(self):
    #     return reverse('profile')


    def save(self, *args, **kwargs):
	    super(profile,self).save(*args, **kwargs)


class post(models.Model, HitCountMixin):
        
    title = models.CharField(max_length=1500)
    ingredients = models.TextField()
    content = RichTextField(blank=True, null=True)
    # content = models.TextField()
    date_post = models.DateTimeField(auto_now_add= True)
    author = models.ForeignKey(User,on_delete=models.CASCADE, null=True, blank=True)
    views = models.IntegerField(default=0)
    timing = models.IntegerField(default=0)
    servings = models.IntegerField(default=0)
    type = models.CharField(max_length=100,default="type")
    cuisine = models.CharField(max_length=100,default="cuisine")
    category = models.CharField(max_length=100,default="category")
    # city = models.CharField(max_length=100, default="city")
    likes = models.ManyToManyField(profile, related_name="likes")
    dislikes = models.ManyToManyField(profile, related_name="dislikes")
    favourites = models.ManyToManyField(User, related_name='favourite',default=None,blank=True)
    date_modified = models.DateTimeField(auto_now=True)
    difficulty = models.CharField(max_length=100,default="difficulty")
    hit_count_generic = GenericRelation(HitCount, object_id_field='object_pk', related_query_name='hit_count_generic_relation')
    
    
    def __str__(self):
        return self.title + " - "+self.author.username
        # return self.title + " - "+self.author.username

    def get_date(self):
        return self.date_post.date()

    def get_modified_date(self):
        return self.date_modified.date()

    def get_absolute_url(self):
        return reverse('home')
    
    def read_time(self):
        words_per_minute = 200  # Adjust this based on your content
        total_words = len(self.content.split())
        minutes = total_words / words_per_minute
        return round(minutes)

    def total_likes(self):
        return self.likes.all().count()

    def total_dislikes(self):
        return self.dislikes.all().count()

    def whenpublished(self):
        now = timezone.now()
        
        diff= now - self.date_post

        if diff.days == 0 and diff.seconds >= 0 and diff.seconds < 60:
            seconds= diff.seconds
            
            if seconds == 1:
                return str(seconds) +  "second ago"
            
            else:
                return str(seconds) + " seconds ago"

            

        if diff.days == 0 and diff.seconds >= 60 and diff.seconds < 3600:
            minutes= math.floor(diff.seconds/60)

            if minutes == 1:
                return str(minutes) + " minute ago"
            
            else:
                return str(minutes) + " minutes ago"



        if diff.days == 0 and diff.seconds >= 3600 and diff.seconds < 86400:
            hours= math.floor(diff.seconds/3600)

            if hours == 1:
                return str(hours) + " hour ago"

            else:
                return str(hours) + " hours ago"

        # 1 day to 30 days
        if diff.days >= 1 and diff.days < 30:
            days= diff.days
        
            if days == 1:
                return str(days) + " day ago"

            else:
                return str(days) + " days ago"

        if diff.days >= 30 and diff.days < 365:
            months= math.floor(diff.days/30)
            

            if months == 1:
                return str(months) + " month ago"

            else:
                return str(months) + " months ago"


        if diff.days >= 365:
            years= math.floor(diff.days/365)

            if years == 1:
                return str(years) + " year ago"

            else:
                return str(years) + " years ago"


class photo(models.Model):
    image = models.ImageField(upload_to="images/")
    feed = models.ForeignKey(post, on_delete=models.CASCADE)

    def save(self, *args, **kwargs):
        # If the image field is not empty
        if self.image:
            # Switch storage backend based on environment
            if 'DATABASE_URL' in os.environ:
                # Running on Render (production environment)
                self.image.storage = s3boto3.S3Boto3Storage()
            else:
                # Running locally
                self.image.storage = default_storage
        super().save(*args, **kwargs)
    
    def __str__(self):
        return self.feed.title + " - "+self.feed.author.username



class UserLocation(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    location = models.CharField(max_length=200, default='Location', null=True, blank=True)

    def __str__(self):
        return self.location


class comments(models.Model):
    date_comment = models.DateTimeField(default=timezone.now)
    date_update_comment = models.DateTimeField(default=timezone.now)
    post_super = models.ForeignKey(post,on_delete=models.CASCADE)
    comment_user = models.ForeignKey(User,on_delete=models.CASCADE)
    comment = models.TextField()

    def __str__(self):
        return self.post_super.title +" - "+ self.comment_user.first_name

    def get_date(self):
        return self.date_comment.date()
    

class BlogHistory(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_histories')
    blog_post = models.ForeignKey(post, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.blog_post.title + ' -' + " BlogHistory"

    def time_stamp(self):
        return self.timestamp.date()
    

class Favorite(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    blog = models.ForeignKey(post, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.blog.title + ' -' + " Favorite"
    

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    primary_color = models.CharField(max_length=20, null=True, blank=True, default='#DBCBBD')
    secondary_color = models.CharField(max_length=20, null=True, blank=True, default='#F0ECE3')
    tertiary_color = models.CharField(max_length=20, null=True, blank=True, default='#221e20')
    active_link_color = models.CharField(max_length=20, null=True, blank=True, default='#9F8772')
    hover_color = models.CharField(max_length=20, null=True, blank=True, default='#9C938B')

    theme = models.CharField(max_length=100, null=True, blank=True, default='theme')
    
    neutral_primary = models.CharField(max_length=20, null=True, blank=True, default='#DBCBBD')
    
    neutral_secondary = models.CharField(max_length=20, null=True, blank=True, default='#D8D9DA')

    use_colors_from_image = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username
    


class RedeemedCredit(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    amount = models.IntegerField(validators=[MinValueValidator(0)])
    redeemed_timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user.username} - {self.amount} - {self.redeemed_timestamp.date()}"


class CreditHistory(models.Model):
    CREDIT_ACTIONS = (
        ('earned', 'Earned'),
        ('redeemed', 'Redeemed'),
        ('new_recipe', 'New recipe'),
        ('deleted', 'Deleted'),
    )

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    amount = models.IntegerField(validators=[MinValueValidator(0)])
    earned_timestamp = models.DateTimeField(auto_now_add=True)
    credit_action = models.CharField(max_length=20,null=True, choices=CREDIT_ACTIONS)

    def __str__(self):
        return f"{self.user.username} - {self.amount} - {self.earned_timestamp.date()}"
    

class CreditSpentHistory(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    recipename = models.ForeignKey(post, on_delete=models.CASCADE)
    amount = models.IntegerField()
    spent_timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):

testingapp/templates/testingapp/favourites.html
{% extends 'testingapp/newnavbar_navrail.html' %}

{% load hitcount_tags %}

{% load static %}


{% block css %}
{% endblock %}


{% block title %}
<title>Favourites</title>
{% endblock %}

{% block weather_widget %}
{% endblock %}

{% block sm_weather %}
{% endblock %}

{% block content%}

<body>

{% if user.is_authenticated %}

  <div class="primary-wrapper">

    <div class="secondary-wrapper">

      <div class="container container-flex container-flex-2">

        <main role="main" class="container-main">

          <div class="dynamic-recipes dynamic-header tertiary-wrapper">
                   
            <h1><button class="btn btn-light back-btn" onclick="history.back()"><span class="material-symbols-rounded back-btn-icon">arrow_back</span></button> 
              Favourites
            </h1>

            <div class="dynamic-card-container all-recipes-card-container all-recipes-card-container-secondary">

                {% include 'testingapp/update_recipe_card.html' %}

                   
            </div> 
        
          </div>

        </main>

      </div>

    </div>

    {% include 'testingapp/footer.html' %}

  </div>

{% else %}  <!-- User is unauthenticated then redirect to login page-->

{% endif %}
</body>



<!-- quick view offcanvas -->
{% if all_recipes %} 
{% for post in all_recipes %}
<div class="offcanvas offcanvas-end qv-offcanvas" tabindex="-1" id="quickviewModal{{post.pk}}" aria-labelledby="quickviewModalLabel">
    <div class="offcanvas-header">
      <h5 class="offcanvas-title" id="quickviewModalLabel">Yummy Recipes</h5>
      <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
    </div>
    <div class="offcanvas-body qv-modal-body">
        <article class="article-featured">
            <div class="qv-offcanvas-img-container">
                {% for i in post.photo_set.all %}
                    {% if forloop.counter0 == 0 %}
                        <img src="{{ i.image.url }}" class="article-image qv-offcanvas-img" alt="{{post.title}}">
                    {% endif %}
                    {% empty %}
                        <img src="{% static 'testingapp/media/empty4.jpg' %}" class="modal-rec-img">
                {% endfor %}
            </div>
            
            <div class="qv-offcanvas-title-container">
                <h3 class="article-title">{{post.title}}</h3>
                <p>
                    <ul>
                        <li><img src="{{ post.author.profile.profile_img.url }}" style="width: 30px; height: 30px; border-radius:100px" alt="Image"></li>
                        <li><div class="text-truncate">{{post.author.first_name}} {{post.author.last_name}}</div>  {{post.get_date}} &#11825; {% get_hit_count for post %} views</li>
                    </ul>
                </p>
            </div>

            <div class="qv-offcanvas-table-wrapper">
                <table class="table">
                    
                    <tbody class="qv-table-body">
                    <tr>
                        <th scope="row" colspan="2">Type</th>
                        <td>{{post.type}}</td>
                    </tr>
                    <tr>
                        <th scope="row" colspan="2">Category</th>
                        <td>{{post.category}}</td>
                    </tr>
                    <tr>
                        <th scope="row" colspan="2">Cuisine</th>
                        <td>{{post.cuisine}}</td>
                    </tr>
                    <tr>
                        <th scope="row" colspan="2">Prep time</th>
                        <td>{{post.timing}} min</td>
                    </tr>
                    <tr>
                        <th scope="row" colspan="2">Servings</th>
                        <td>{{post.servings}}</td>
                    </tr>
                    <tr>
                      <th scope="row" colspan="2">Difficulty</th>
                      <td>{{post.difficulty}}</td>
                    </tr>
                    <tr>
                        <th scope="row" colspan="2">Likes</th>
                        <td>{{post.total_likes}}</td>
                    </tr>
                    <tr>
                        <th scope="row" colspan="2">Dislikes</th>
                        <td>{{post.total_dislikes}}</td>
                    </tr>
                    </tbody>
                </table>
            </div>
            
            
            <!-- <a href="#" class="article-read-more">CONTINUE READING</a> -->
        </article>

        <div class="footer-area">
            <a href="{% url 'viewpost' post.pk %}" class="qv-offcanvas-footer-link">View <span class="material-symbols-rounded qv-offcanvas-link-icon">trending_flat</span></a>
        </div>
    </div>
</div>
{% endfor %}
{% endif %}


{% endblock %}

testingapp/templates/testingapp/footer.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  
  <link rel="icon" type="image/x-icon" href="{% static 'testingapp/media/logo2.ico' %}">

  
  <link id="mystylesheet" rel="stylesheet" href="{% static 'testingapp/footer.css' %}">


</head>

{% block title %}
<title>New Navbar Navrail</title>
{% endblock %}

<body>

    {% block content %}


    <footer class="footer" id="footer">
        <div class="footer-waveline" id="footerwaveline"></div>

        <div class="footer-container">
            <div class="column">
                <img src="{% static 'testingapp/media/NewLogo.png' %}" alt="Brand Icon" class="footer-brand-logo">
                <!-- <h2>Brand Name</h2> -->
                <p>
                    Welcome to Yummy Recipes! Indulge your taste buds with our delightful 
                    collection of mouthwatering recipes from around the world. Whether 
                    you're a seasoned chef or a home cook, our easy-to-follow recipes 
                    cater to all skill levels, allowing you to create delicious dishes.
                </p>
            </div>
            <div class="column">
                <h5>Social</h5>
                <ul>
                    <li><a href="#" class="footerlinks">Facebook</a></li>
                    <li><a href="#" class="footerlinks">Twitter</a></li>
                    <li><a href="#" class="footerlinks">Instagram</a></li>
                </ul>
            </div>
            <div class="column">
                <h5>Overview</h5>
                <ul>
                    <li><a href="#" class="footerlinks">About Us</a></li>
                    <!-- <li><a href="#" class="footerlinks">Library 2</a></li> -->
                </ul>
            </div>

        </div>

        <div class="footer-bottom">
            <div class="hstack gap-1">
                <div class="p-1"><h3>Yummy Recipes</h3></div>
                <div class="p-1">&copy; all rights reserved.</div>
              </div>
        </div>

    </footer>
    
{% endblock %}

</body>
</html>

testingapp/templates/testingapp/updateprofile.html
{% extends 'testingapp/newnavbar_navrail.html' %}

{% load hitcount_tags %}

{% load static %}

{% block title %}
<title>Update profile</title>
{% endblock %}

{% block weather_widget %}
{% endblock %}

{% block sm_weather %}
{% endblock %}


{% block content%}

<body>

    <div class="primary-wrapper">
        
        <div class="secondary-wrapper">

            <div class="container container-flex container-flex-2">

                <main role="main" class="home-main container-main">

                    <div class="dynamic-recipes dynamic-header profile-heading">
                        
                        <h1><button class="btn btn-light back-btn" onclick="history.back()"><span class="material-symbols-rounded back-btn-icon">arrow_back</span></button>
                            Update profile
                        </h1>


                        <div class="dynamic-card-container">
                            
                            <div class="update-profile-card">

                            <form method="post" enctype="multipart/form-data">
                                {% csrf_token %}

                                <div class="row mb-3 upro-first-row">
                                  <label for="inputEmail3" class="col-md-5 col-form-label uprofile-form-label uprofile-first-label">Currently:</label>

                                    <div class="col">
                                        <div class="profile-form-input profile-header uprofile-img">
                                            
                                            <div class="container text-center">
                                                <div class="row">
                                                    <div class="col">
                                                        <img src="{{ user.profile.profile_img.url }}" alt="" srcset="" class="profile-image">
                                                    </div>

                                                    <div class="col">
                                                        <img id="display-image" class="new-image">
                                                    </div>
                                                </div>
                                            </div>

                                        </div>
                                    </div>
                                </div>
                            

                                <div class="row upro-second-row">
                                    <div class="row mb-3 upro-input-container">
                                        <label for="id_profile_img" class="col-md-5 col-form-label uprofile-form-label">Change</label>
    
                                        <div class="col">
                                            <input type="file" class="form-control uprofile-input" name="profile_img" accept="image/*" id="id_profile_img">
                                        </div>
                                    </div>

                                    <div class="row mb-3 upro-input-container">
                                        <label for="inputEmail3" class="col-md-5 col-form-label uprofile-form-label">First Name</label>
                                        
                                        <div class="col">
                                          <input type="text" class="form-control uprofile-input" name="first_name" value="{{ user.first_name }}" id="id_first_name">
                                        </div>
                                      </div>
      
                                      <div class="row mb-3 upro-input-container">
                                        <label for="inputPassword3" class="col-md-5 col-form-label uprofile-form-label">Last Name</label>
                                        
                                        <div class="col">
                                          <input type="text" name="last_name" class="form-control uprofile-input" value="{{ user.last_name }}" id="id_last_name">
                                        </div>
                                      </div>
      
                                      <div class="row mb-3 upro-input-container">
                                          <label for="inputPassword3" class="col-md-5 col-form-label uprofile-form-label">Email</label>
      
                                          <div class="col">
                                              <input type="text" class="form-control uprofile-input" name="email" value="{{ user.email }}" id="id_email">
                                          </div>
                                      </div>
                      
                                      <div class="row mb-3 upro-input-container">
                                          <label for="id_gender" class="col-md-5 col-form-label uprofile-form-label">Gender</label>
      
                                          <div class="col">
                                              <!-- <input type="text" class="form-control uprofile-input" name="gender" maxlength="10" value="{{user.profile.gender}}" required="" id="id_gender"> -->
                                            
                                              <select name="gender" class="form-control uprofile-input" id="id_gender">
                                                {% for choice in gender_choices %}
                                                    {% if user.profile.gender == choice.0 %}
                                                        <option value="{{ choice.0 }}" selected>{{ choice.1 }}</option>
                                                    {% else %}
                                                        <option value="{{ choice.0 }}">{{ choice.1 }}</option>
                                                    {% endif %}
                                                {% endfor %}
                                              </select>
                                          </div>
                                      </div>
                      
                                      <div class="row mb-3 upro-input-container">
                                          <label for="id_dob" class="col-md-5 col-form-label uprofile-form-label">Dob</label>
      
                                          <div class="col">
                                              <input type="date" class="form-control uprofile-input" name="dob" maxlength="20" onfocus="(this.type='date')" onblur="(this.type='date')" value="{{user.profile.dob|date:"Y-m-d"}}" placeholder="{{user.profile.dob}}" required id="id_dob">
                                          </div>
                                          <p class="card-text"><small class="text-muted">** mm / dd / yyyy</small>
                                      </div>
                      
                                      <div class="row mb-3 upro-input-container">
                                          <label for="id_bio" class="col-md-5 col-form-label uprofile-form-label">Bio</label>
                                          
                                          <div class="col">
                                                <textarea name="bio" class="form-control uprofile-input" maxlength="114" required="" value="{{ user.profile.bio }}" id="id_bio">{{ user.profile.bio }}</textarea>                                        
                                          </div>
                                          <p class="card-text"><small class="text-muted">** maximum 100 characters</small>
                                      </div>
                                </div>

                                <div class="bottom-links upro-btm-lnk">
                                    <div class="child-1 edit-links">
                                        <button id="update-profile-btn"><span class="material-symbols-rounded share-recipe-icon">check</span> <span>Update</span></button>
                                    </div>
                                </div>
                            </form>
                            
                            </div>

                        </div>
                    </div>

                </main>
                
            </div>
 
        </div>

    </div>
    
    
</body>



<script>
    const image_input = document.querySelector("#id_profile_img");

    image_input.addEventListener("change", function() {
    const reader = new FileReader();
    reader.addEventListener("load", () => {
        const uploaded_image = reader.result;
        document.querySelector("#display-image").style.backgroundImage = `url(${uploaded_image})`;
    });
    reader.readAsDataURL(this.files[0]);
    });


    $(document).ready(function(){
  	$('[data-toggle="tooltip"]').tooltip();   
	});
</script>


{% endblock %}